spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: url
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password

  sql:
    init:
      mode: always
      platform: local

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  session:
    jdbc:
      initialize-schema: always

  #social
  security:
    oauth2:
      client:
      registration:
        google:
          client-id: clientId
          client-secret: clientSecret
          scope:
            - 'https://www.googleapis.com/auth/userinfo.email'
            - 'https://www.googleapis.com/auth/userinfo.profile'
            - 'https://www.googleapis.com/auth/user.birthday.read'
            - 'https://www.googleapis.com/auth/user.phonenumbers.read'

